export type {
  TechAlert,
  TechIncomingRequest,
  TechIncomingStatus,
  TechMessage,
  TechPart,
  TechProfile,
  TechRepairJob,
  TechRepairStage,
  TechThread,
} from "./model/types";
export {
  getTechIncoming,
  getTechRepair,
  getTechThread,
  techAlerts,
  techCompleted,
  techIncoming,
  techMessagesByThread,
  techPartsCatalog,
  techProfile,
  techRepairs,
  techTemplates,
  techThreads,
} from "./model/mockTech";
